### ISSUE TITLE
how to implement this?

### ISSUE THREAD

**Issue by KraXen72** [ryanccn/discord-css-mappings#1]
i want to update my discord css, https://github.com/KraXen72/rosebox/tree/master/discord to use your auto-generating mappings. how can i do so? i am prepared to rewrite classes if needed.

**Comment by ryanccn** [comment]
Hey there, 

At the moment there is no way to use this other than writing your own script to pull from the JSON here and rewrite CSS classes, but I am working on a PostCSS plugin to make things easier :p

**Comment by KraXen72** [comment]
my theme is fully in css and i utilize nesting heavily - so the nesting could provide userful information to the postcss plugin knowing which class to properly resolve

**Comment by ryanccn** [comment]
The monorepo rewrite is done! Refer to https://github.com/ryanccn/discord-css-mappings/blob/main/packages/postcss-plugin/README.md to see how to use the PostCSS plugin.
